### ISSUE TITLE
More branches?

### ISSUE THREAD

**Issue by nathanhilbert** [openspending/spendb#1]
Thanks for continuing to rock on this.  For my own sanity, do you think it possible to branch a bit more for new features, as I'm going to assume whatever is in the master branch works without too much hassle.

**Comment by pudo** [comment]
You're absolutely right. I've slightly lost control of the refactor and need to cheat to make the tests pass (specifically, some of the dataset editor controllers are broken right now and the effort needed to fix them exceeds the amount of work needed to do a new thing in Angular). 

My recommendation would be to stay on something like https://github.com/openspending/spendb/commit/18097fa9086d609ac47d9ccfcfbcaff274ad71a9 if you need WYSIWYG dataset editing. 

I apologize for the confusion.

**Comment by nathanhilbert** [comment]
Great.  Thanks!
