### ISSUE TITLE
Missing dependencies in requirements.txt

### ISSUE THREAD

**Issue by mattfullerton** [openspending/spendb#36]
billiard
markdown
kombu

**Comment by pudo** [comment]
Odd, these should be pulled in indirectly. Are you doing a normal ``pip install -r requirements.txt``?

**Comment by mattfullerton** [comment]
Yep, but I was on a mac, so all bets are off...

**Comment by pudo** [comment]
Hey! Leave britney alone :) Seriously, though: are you using a virtualenv without site packages? That should create a clean slate and tell us if we have a problem here.

**Comment by mattfullerton** [comment]
I believe I did virtualenv ./pyenv --distribute
